# Generated by Django 2.1 on 2018-08-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0011_auto_20180820_1734'),
        ('jobs', '0002_auto_20180820_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasureBoxGacha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasure_box_gachas', to='items.Item')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasure_box_gachas', to='jobs.Job')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasure_box_gachas', to='items.ItemRank')),
            ],
        ),
    ]
