# Generated by Django 2.1 on 2018-08-18 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemInventory',
            new_name='Inventory',
        ),
    ]
