# Generated by Django 2.1 on 2018-08-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_auto_20180818_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='stat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
