# Generated by Django 2.1.7 on 2020-02-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TikiProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=2000)),
                ('current_lowest_price', models.BigIntegerField(default=1000000000)),
                ('lowest_price', models.BigIntegerField(default=1000000000)),
                ('error', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
