# Generated by Django 2.1 on 2018-08-18 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=50)),
                ('max_star', models.IntegerField(default=5)),
                ('max_level', models.IntegerField(default=5)),
                ('emblem_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStatRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('fixed', models.BooleanField(default=False)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_range', to='items.ItemRank')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_range', to='items.ItemStat')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='itemsubtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='items.ItemType'),
        ),
        migrations.AddField(
            model_name='itemstatrange',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_range', to='items.ItemSubType'),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.ItemName'),
        ),
        migrations.AddField(
            model_name='item',
            name='stat_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.ItemStatRange'),
        ),
    ]
