# Generated by Django 2.1 on 2018-08-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('items', '0003_remove_itemsubtype_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stat_range',
        ),
        migrations.AddField(
            model_name='item',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='item',
            name='stats',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='items.ItemStat'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.ItemSubType'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.ItemType'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ItemName',
        ),
    ]
