# Generated by Django 2.1 on 2018-08-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20180820_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstatrange',
            name='emblem',
            field=models.BooleanField(default=False),
        ),
    ]
