# Generated by Django 2.1 on 2018-08-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_itemstatrange_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stats',
            field=models.ManyToManyField(blank=True, related_name='items', to='items.ItemStat'),
        ),
    ]
