# Generated by Django 2.1 on 2018-08-20 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('items', '0008_auto_20180820_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstatrange',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stat_range', to='jobs.Job'),
        ),
    ]
