# Generated by Django 2.1 on 2018-08-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_itemstatrange_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstatrange',
            name='job_specific',
            field=models.BooleanField(default=True),
        ),
    ]
