# Generated by Django 2.1 on 2018-08-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_itemstatrange_job_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstatrange',
            name='base',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='itemstatrange',
            name='max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='itemstatrange',
            name='min',
            field=models.FloatField(default=0.0),
        ),
    ]
