# Generated by Django 2.1.3 on 2018-12-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrophyRoomConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_channel_id', models.BigIntegerField(help_text='Put ID of the channel to display trophy list here.')),
                ('trophy_list_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trophy Room Config',
                'verbose_name_plural': 'Trophy Room Config',
            },
        ),
    ]
