# Generated by Django 2.1 on 2018-08-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GachaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rare_item_count', models.IntegerField(default=0)),
                ('epic_item_count', models.IntegerField(default=0)),
                ('unique_item_count', models.IntegerField(default=0)),
                ('legendary_item_count', models.IntegerField(default=0)),
                ('unique_emblem_item_count', models.IntegerField(default=0)),
                ('legendary_emblem_item_count', models.IntegerField(default=0)),
                ('jewel_owned', models.IntegerField(default=0)),
                ('jewel_used', models.IntegerField(default=0)),
                ('daily_check', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
