# Generated by Django 2.1 on 2018-08-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180821_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='gachainfo',
            name='discord_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DiscordUser'),
        ),
    ]
