# Generated by Django 2.1 on 2018-08-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_gachainfo_discord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gachainfo',
            name='discord_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gacha_info', to='users.DiscordUser'),
        ),
    ]
