# Generated by Django 2.1.7 on 2019-03-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_investigationinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='monument_channel_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='monument_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
