# Generated by Django 2.1.7 on 2019-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honkaiimpactdaily',
            options={'verbose_name': 'Honkai Impact Daily', 'verbose_name_plural': 'Honkai Impact Dailies'},
        ),
        migrations.AlterField(
            model_name='honkaiimpactdaily',
            name='emoji',
            field=models.CharField(help_text='Must be a Unicode character', max_length=2),
        ),
    ]
