# Generated by Django 2.1.7 on 2019-05-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0002_auto_20190506_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='honkaiimpactdaily',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='honkaiimpactdaily',
            name='emoji',
            field=models.CharField(help_text='Must be a Unicode character', max_length=2, unique=True),
        ),
    ]
