# Generated by Django 2.1.7 on 2019-05-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0003_auto_20190506_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honkaiimpactdaily',
            name='emoji',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
