# Generated by Django 2.1.7 on 2019-05-06 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0004_auto_20190506_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='honkaiimpactdaily',
            name='sent_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 10, 57, 2, 409036, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
