# Generated by Django 2.1.7 on 2019-05-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0005_honkaiimpactdaily_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='honkaiimpactdaily',
            name='message_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
