# Generated by Django 2.1.7 on 2019-06-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0007_auto_20190506_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='honkaiimpactdaily',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
