# Generated by Django 2.1.3 on 2018-12-22 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Give your case a cool name! For management purposes.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional. For management purposes, too.', max_length=2000)),
                ('status', models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('active', 'Active'), ('closed', 'Closed'), ('failed', 'Failed')], default='unknown', help_text='Optional. This will change depending on the scenarios.<br/>• <strong>Unknown</strong> is the default status. Mark it as <strong>Active</strong> after you set the clues, then all the Clues are available to be discovered.<br/>• Mark as <strong>Active</strong> when you want to activate the case. <strong>Only 1 Active case at a time.</strong><br/>• Mark as <strong>Closed</strong> when the case is complete.<br/>• Mark as <strong>Failed</strong> when the case is not solved.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional, give it a name to easier distinguish with other clues.', max_length=200)),
                ('channel_id', models.BigIntegerField(help_text='The channel ID the clues are in. Enable Discord Developer Mode and right-click on the channel to Copy ID.')),
                ('triggers', models.CharField(help_text='A list of trigger words separated by semicolons (;). Eg: trash;trash can;recycle bin', max_length=200)),
                ('message', models.TextField(help_text='Discord markdown enabled.<br/>• To mention someone, use <@user_id>.<br/>• To mention a role, use <@&role_id>.<br/>• To mention a channel, use <#channel_id>.', max_length=2000)),
                ('is_clue', models.BooleanField(default=False, help_text="Check this to make this a Clue, otherwise it's just a normal message with no clues in it.")),
                ('is_pinned', models.BooleanField(default=False, help_text='A pinned clue is one that has been discovered.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pinned_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('case', models.ForeignKey(help_text='Select one of the Cases or click that + button to create one.', on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='investigations.Case')),
            ],
        ),
    ]
