# Generated by Django 2.1.3 on 2018-12-22 01:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='actions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
