# Generated by Django 2.1.3 on 2018-12-22 05:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0002_hint_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='actions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
