# Generated by Django 2.1.3 on 2018-12-22 06:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_auto_20181222_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='required_hints',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
    ]
